# Importância do Numpy
## Aplicativos Numpy com outras bibliotecas
### NumPy com Pandas
<p>Pandas é uma das bibliotecas mais importantes em Python para análise de dados, fornece recuros de alto desempenho para tratamento e análise de dados. O Dataframe do Pandas utiliza o NumPy para cálculos mais rápidos.</p>

### NumPy com Matplotlib
<p>É uma ferramenta muito útil para trabalhar com representações gráficas. Consiste em uma ampla gama de funções para traçar gráficos e também manipulá-los. O Matplot utiliza também adota o NumPy entre suas dependencias.</p>

### NumPy com SciPy
<p>Scipy é biblioteca científica mais importante em python. Ele foi construído sobre as funcionalidades do NumPy, com funcionalidades avançadas no SciPy para cálculos científicos com maior desempenho matemático.</p>

### Instalação de NumPy
<p>Usar o comando</p>

<p>pip install numpy</p>

### Importar NumPy
<p>import numpy</p>

In [1]:
import numpy

meu_array = numpy.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


# Padrão de importação do NumPy com o alias np


In [2]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


# Como checar a versão do NumPy
<p>Acessar o propriedade version do pacote.</p>

In [3]:
print(np.__version__)

1.26.4


# Criando matrizes

- O objeto de matriz em NumPy é chamado de ndarray
- Usar a função array() para criar a matriz

In [7]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

meu_array_str = np.array([10,20,30,40,'50',60,70,80,90,100])

print(meu_array, meu_array_str)

print(type(meu_array), type(meu_array_str))

meu_array.dtype, meu_array_str.dtype

[ 10  20  30  40  50  60  70  80  90 100] ['10' '20' '30' '40' '50' '60' '70' '80' '90' '100']
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


(dtype('int32'), dtype('<U11'))

<p>Pode-se passar lista, tupla ou qualquer objeto do tipo array para a função array()</p>

# Usando uma tupla para criar uma matriz NumPY:

In [5]:
meu_array = np.array((10,20,30,40,50,60,70,80,90,100))

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


# Usando um set para criar uma matriz NumPy:

In [8]:
meu_array = np.array({10,20,30,40,50,60,70,80,90,100})

print(meu_array)

print(type(meu_array))

{100, 70, 40, 10, 80, 50, 20, 90, 60, 30}
<class 'numpy.ndarray'>


# Dimensões em matrizes

## Matrizes 0-D
- Matrizes 0-D, ou escalares, são os elementos de uma matriz.
- Cada valor em uma matriz é uma matriz 0-D

In [9]:
meu_array = np.array(100)

print(meu_array)

print(type(meu_array))

100
<class 'numpy.ndarray'>


# Matrizes 1-D ou unidimensional

Matriz que possui matrizes 0-D como seus elementos. São os arrays mais comuns e básicos.

In [10]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

print(meu_array)

print(type(meu_array))

[ 10  20  30  40  50  60  70  80  90 100]
<class 'numpy.ndarray'>


# Utilizam tipos fixos para todos os elementos

Os tipos serão convertidos para que sejam do mesmo tipo

In [13]:
meu_array = np.array([10,20,30,40.5,50,60,70,80,90,100])

print(meu_array)

print(type(meu_array))

[ 10.   20.   30.   40.5  50.   60.   70.   80.   90.  100. ]
<class 'numpy.ndarray'>


In [11]:
meu_array = np.array([10,20,30,40,50,60,70,'80','90',100])

print(meu_array)

print(type(meu_array))

['10' '20' '30' '40' '50' '60' '70' '80' '90' '100']
<class 'numpy.ndarray'>


# Matrizes 2-D

Matriz que possui matrizes 1-D como seus elementos, geralmente usada para representar matrizes.

In [17]:
meu_array = np.array([[10,20,30],
                     [40,50,60]])

print(meu_array)

print(type(meu_array))

[[10 20 30]
 [40 50 60]]
<class 'numpy.ndarray'>


# Array 3-D
Array que possui arrays 2-D (matrizes) como seus elementos

In [18]:
meu_array = np.array(
    [
        [
        [10,20,30],
         [40,50,60]
         ],
        [
        [10,20,30],
         [40,50,60]
         ]
     ]
    )

print(meu_array)

print(type(meu_array))

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 60]]]
<class 'numpy.ndarray'>


# Obtendo a quantidade de dimensões do array
* Utilize o atributo do objeto ndarray.

In [19]:
meu_array = np.array(42)

print(meu_array.ndim)

0


In [21]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

print(meu_array.ndim)

1


In [22]:
meu_array = np.array([[10,20,30],
                     [40,50,60]])

print(meu_array.ndim)

2


In [23]:
meu_array = np.array(
    [
        [
        [10,20,30],
         [40,50,60]
         ],
        [
        [10,20,30],
         [40,50,60]
         ]
     ]
    )

print(meu_array.ndim)

3


# Matrizes com muitas dimensões
- Uma matriz pode ser criada com qualquer número de dimensões, usando o argumento ndim

In [24]:
meu_array = np.array([21,22,23,24,25], ndmin=5)

print(meu_array)

[[[[[21 22 23 24 25]]]]]


# Criando arrays vazios ou com valores predefinidos

* Sem valor

In [25]:
meu_array = np.empty((4,))

print(meu_array)

print(meu_array.ndim)

[0.00000000e+000 1.05547584e-311 1.05547584e-311 1.05547584e-311]
1


In [26]:
meu_array = np.empty((3,3))

print(meu_array)

print(meu_array.ndim)

[[1.05547584e-311 1.05547584e-311 1.05547584e-311]
 [4.94065646e-324 1.05548495e-311 1.05550603e-311]
 [0.00000000e+000 7.41098469e-323 1.05548479e-311]]
2


* indicando 1 como valor

In [28]:
meu_array = np.ones((3,3))

print(meu_array)

print(meu_array.ndim)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
2


* indicando 0 como valor

In [29]:
meu_array = np.zeros((3,3))

print(meu_array)

print(meu_array.ndim)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
2


* indicando o valor desejado

In [30]:
meu_array = np.full((3,3),99)

print(meu_array)

print(meu_array.ndim)

[[99 99 99]
 [99 99 99]
 [99 99 99]]
2


# Adicionando e removendo elementos

## insert(arr,obj, valores[,eixo])

insira valores ao longo do eixo fornecido antes dos índices fornecidos.


In [31]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

print(meu_array)

novo_array = np.insert(meu_array,3,[888,999])

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30 888 999  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


## append(arr, valores[,eixo])

In [33]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

print(meu_array)

novo_array = np.append(meu_array,[888,999])

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100 888 999]
[ 10  20  30  40  50  60  70  80  90 100]


# delete(arr,obj[,eixo])

Retorne uma nova matriz com submatrizes ao longo de um eixo excluído

In [34]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100])

print(meu_array)

novo_array = np.delete(meu_array, [1,3,5])

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  30  50  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


# unique(ar [return_index, return_inverse,...])

Encontre os elementros exclusivos de uma matriz

In [35]:
meu_array = np.array([10,20,30,40,50,60,70,80,90,100,10,20,30,40,50,60,70,80,90,100,10,20,30,40,50,60,70,80,90,100])

print(meu_array)

novo_array = np.unique(meu_array)

print(novo_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50  60  70  80
  90 100  10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100  10  20  30  40  50  60  70  80
  90 100  10  20  30  40  50  60  70  80  90 100]
