# Numpy - Indexação de Arrays e Matrizes
## NumPy (Numerical Python)
- Biblioteca python usada para trabalhar com álgebra linear, arrays e matrizes.
- Criada em 2005 por Travis Oliphant como projeto de código aberto.
- Fornecer um objeto de matriz que é até 50x mais rápido que as listas tradicionais do Python
- Array NumPy é armazenados em um local contínuo na memória;
- É otimizado para funcionar com as arquiteturas de CPU mais recentes;
- Utiliza tipos fixos;
- Demandam menos espaço de memória para mesma quantidade de elementos;
- SIMD - Processamento vetores Single instruction, multiple data (SIMD);
- Utilização eficente de cache do processador
- Mais versatilidade nas operações com arrays (ex. multiplicação)
- Utilizado como base para calculos matemáticos, Plotagem de gráficos (Matplotlib), backend do pandas, base para algoritmos de machine learning.
- É codificado parcialmente em Python, mas a maioria das partes que requerem computação rápida são escritas em C ou C ++.
- O objeto array em NumPy é chamado ndarray.
- O ndarray fornece várias funções de suporte que facilitam muito se uso.
- São indicados para situações em que velocidade e recursos são muito importantes.

# Indexação de matriz NumPy
 - Pode-se acessar um elemento da matriz referindo-se ao seu número de índice.
 - Os índices nas matrizes NumPy começam com 0

In [2]:
import numpy as np

meu_array = np.array([21, 22, 23, 24, 25])

meu_array[0], meu_array[-1]

(21, 25)

# Acessar matrizes 2-D
 - Pode-se usar números inteiros separados por vírgula [dimensão, indice do elemento]

In [3]:
meu_array = np.array([
                      [21, 22, 23, 24, 25], 
                      [26, 27, 28, 29, 30]
                      ])

print('O terceiro elemento da segunda dimensão: ', meu_array[1, 2])

O terceiro elemento da segunda dimensão:  28


In [4]:
meu_array = np.array([
                      [21, 22, 23, 24, 25], 
                      [26, 27, 28, 29, 30]
                      ])

print('O segundo elemento da primeira dimensão: ', meu_array[0, 1])

O segundo elemento da primeira dimensão:  22


# Acessar matrizes 3-D
 - Pode-se usar inteiros separados por vírgula[dimensão, dimensão, elemento].

In [5]:
meu_array = np.array([
                        [
                          [10, 20, 30], 
                          [40, 50, 60]
                        ], 
                        [
                          [70, 80, 90], 
                          [100, 110, 120]
                        ]
                      ])

print(meu_array[0, 1, 2])

print(meu_array[1, 0, 0])

print(meu_array[0, 0, 1])

60
70
20


# Indexação Negativa
 - Pode-se usar a indexação negativa para acessar uma matriz a partir do final.

In [6]:
meu_array = np.array([
                        [
                        [10, 20, 30], 
                        [40, 50, 60]
                        ], 
                        [
                        [70, 80, 90], 
                        [100, 110, 120]
                        ]
                      ])

print(meu_array[-1, -1, -1])

print(meu_array[-2, -2, -2])

120
20


# Obtendo um recorte da matriz NumPy

## Fatiar matrizes
- array[indice início: índice fim] ou
- array[indice início : índice fim : passo (padrao 1)

In [7]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[1:5])

[20 30 40 50]


In [8]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[3:])

[ 40  50  60  70  80  90 100]


In [9]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[:4])

[10 20 30 40]


# Recorte da Matriz usando Indexação Negativa
 - Utilize a posição a partir do final como índices.

In [10]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[-5:-2])

[60 70 80]


In [11]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[-9:])

[ 20  30  40  50  60  70  80  90 100]


# Recorte usando argumento step
- Use esse argumento para indicar os saltos que devem durante o seleção dos elementos do recorte

In [12]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[0:9:3])

[10 40 70]


In [13]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[2: :2])

[30 50 70 90]


In [14]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[ : 4 :2])

[10 30]


# Retornar todos os elementos de toda a matriz:

In [15]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[:])
print(meu_array[::])
print(meu_array[::1])

[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [16]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array[: : 2])
print(meu_array[: : 3])
print(meu_array[: : 4])

[10 30 50 70 90]
[ 10  40  70 100]
[10 50 90]


# Recorte em matrizes 2-D
## Retornar uma lista de valores de determinada linha da matriz 2-D

In [17]:
meu_array = np.array([
                      [10, 20, 30, 40, 50], 
                      [60, 70, 80, 90, 100],
                      [160, 170, 180, 190, 1100], 
                      [260, 270, 280, 290, 2100]
                      ])

print(meu_array[0, 1:5])

[20 30 40 50]


In [18]:
print(meu_array[1, :4])

[60 70 80 90]


In [19]:
print(meu_array[2,-3:])

[ 180  190 1100]


In [20]:
print(meu_array[-1,-3:])

[ 280  290 2100]


# Retornar uma lista de valores de determinada coluna da matriz 2-D

In [21]:
meu_array = np.array([
                      [10, 20, 30, 40, 50], 
                      [60, 70, 80, 90, 100],
                      [160, 170, 180, 190, 1100], 
                      [260, 270, 280, 290, 2100]
                      ])

print(meu_array[:, 1])

[ 20  70 170 270]


In [22]:
print(meu_array[:, 2])

[ 30  80 180 280]


In [23]:
print(meu_array[:, 0:2])

[[ 10  20]
 [ 60  70]
 [160 170]
 [260 270]]


In [24]:
print(meu_array[1:3, 0:2])

[[ 60  70]
 [160 170]]


In [25]:
print(meu_array[-3:, -1])

[ 100 1100 2100]


In [26]:
print(meu_array[-3:, -2:])

[[  90  100]
 [ 190 1100]
 [ 290 2100]]
