# Numpy - Tipologia de Dados de Arrays
## Tipos de dados NumPy
## Tipos de dados em Python
- strings: usado para representar dados de texto;
- integer: usado para representar números inteiros positivos e negativos;
- float: usado para representar números reais.
- boolean: usado para representar Verdadeiro ou Falso.
- complex: usado para representar um número em um plano complexo. por exemplo. 1,0 + 2,0j, 1,5 + 2,5j

## Tipos de dados em NumPy e os caracteres usados ​​para representá-los.
- i - integer
- b - boolean
- u - unsigned integer
- f - float
- c - complex float
- m - timedelta
- M - datetime
- O - object
- S - string
- U - unicode string

## Checar o tipo de dados de uma matriz
### Pode se usar propriedade dtype para retornar o tipo de dados da matriz:

In [1]:
import numpy as np

meu_array = np.array([21, 22, 23, 24, 25])

print(meu_array.dtype)

int32


In [2]:
meu_array = np.array(['José', 'Maria', 'João', 'Noêmia'])

print(meu_array.dtype)

print(meu_array)

<U6
['José' 'Maria' 'João' 'Noêmia']


## Definir o tipo de dado na Criação de matrizes
- Usando argumento opcional: dtype da função array()
- Para os tipos i, u, f, S , U também é possível indicar o tamanho.

In [3]:
meu_array = np.array([21, 22, 23, 24, 25], dtype=str)

print(meu_array)

print(meu_array.dtype)

['21' '22' '23' '24' '25']
<U2


### Para os tipos i, u, f, S , U também é possível indicar o tamanho.

### Obserse o que ocorre se extrapolar o tamanho

In [4]:
meu_array = np.array([21, 22, 23, 24, 25, 2323423423], dtype='S3')

print(meu_array)

print(meu_array.dtype)

[b'21' b'22' b'23' b'24' b'25' b'232']
|S3


In [5]:
meu_array = np.array([21, 22, 23, 24, 12312312323234], dtype='i8')

print(meu_array)

print(meu_array.dtype)

[            21             22             23             24
 12312312323234]
int64


- Ocorrerá erros e o valor não puder ser convertido para o tipo especificado

In [6]:
meu_array = np.array(['João', '12', '143'], dtype='i')

ValueError: invalid literal for int() with base 10: 'João'

## Conversão de tipo de dados em matrizes
- Utilize o método astype() para criar uma cópia da matriz convertida para o novo tipo de dado.
- Como argumento podem ser passadas tanto as letras dos tipos quanto o nomes dos tipos do python.

In [7]:
meu_array = np.array([1.1, 2.1, 3.1])

novo_array = meu_array.astype('i')

print(novo_array)

print(novo_array.dtype)

[1 2 3]
int32


In [8]:
novo_array = meu_array.astype('U')

print(novo_array)

print(novo_array.dtype)

['1.1' '2.1' '3.1']
<U32


In [9]:
meu_array = np.array([
                      [1.1, 2.1, 3.1],
                      [4.1, 5.1, 6.1]
                      ])

novo_array = meu_array.astype('i8')

print(novo_array)

print(novo_array.dtype)

[[1 2 3]
 [4 5 6]]
int64


In [10]:
meu_array = np.array([1.1, 2.1, 3.1])

novo_array = meu_array.astype(int)

print(novo_array)

print(novo_array.dtype)

[1 2 3]
int32


### Exemplo Altere o tipo de dados de inteiro para booleano:

In [11]:
meu_array = np.array([1, 0, 3])

novo_array = meu_array.astype(bool)

print(novo_array)

print(novo_array.dtype)

[ True False  True]
bool


## NumPy Array Copy vs View
- Copy: retorna uma uma nova matriz
- View: apenas uma visualização da matriz original, e as alterações afetarão a matriz original e vice-versa

In [12]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
copia = meu_array.copy()
copia[0] = 42

print(meu_array)
print(copia)
print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 42  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]


In [13]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
visao = meu_array.view()
visao[0] = 250

print(meu_array)
print(visao)

[250  20  30  40  50  60  70  80  90 100]
[250  20  30  40  50  60  70  80  90 100]


In [14]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(meu_array)
visao = meu_array
visao[0] = 250


print(visao)
print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[250  20  30  40  50  60  70  80  90 100]
[250  20  30  40  50  60  70  80  90 100]


## Checar se uma matriz é um cópia
- As cópias possuem os dados e as visualizações não.
- O atributo base pode ser usado para verificar se a matriz possuir os dados.

In [15]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

copia = meu_array.copy()
visao = meu_array.view()

print(copia.base)
print(visao.base)

None
[ 10  20  30  40  50  60  70  80  90 100]
