# Numpy - Interação com Arrays e Matrizes

## Fazendo iteração em NumPy Array
- Utilize forloop para iterar por cada elemento de um array;
- Utilize loops aninhados para iterar nos elementos de cada

### iteração em Arrays 1-D

In [1]:
import numpy as np

meu_array = np.array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40])

for x in meu_array:
  print(x, end=', ')

1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 

### Iteração em matriz 2-D

In [2]:
meu_array = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])

for x in meu_array:
  print(x)

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]
[21 22 23 24 25 26 27 28 29 30]
[31 32 33 34 35 36 37 38 39 40]


In [3]:
meu_array = np.array([[1,2,3,4,5,6,7,8,9,10],
              [11,12,13,14,15,16,17,18,19,20],
              [21,22,23,24,25,26,27,28,29,30],
              [31,32,33,34,35,36,37,38,39,40]])

for x in meu_array:
  print('linha:', x)
  for y in x:
    print('coluna: ', y, end='; ')
  print('')

linha: [ 1  2  3  4  5  6  7  8  9 10]
coluna:  1; coluna:  2; coluna:  3; coluna:  4; coluna:  5; coluna:  6; coluna:  7; coluna:  8; coluna:  9; coluna:  10; 
linha: [11 12 13 14 15 16 17 18 19 20]
coluna:  11; coluna:  12; coluna:  13; coluna:  14; coluna:  15; coluna:  16; coluna:  17; coluna:  18; coluna:  19; coluna:  20; 
linha: [21 22 23 24 25 26 27 28 29 30]
coluna:  21; coluna:  22; coluna:  23; coluna:  24; coluna:  25; coluna:  26; coluna:  27; coluna:  28; coluna:  29; coluna:  30; 
linha: [31 32 33 34 35 36 37 38 39 40]
coluna:  31; coluna:  32; coluna:  33; coluna:  34; coluna:  35; coluna:  36; coluna:  37; coluna:  38; coluna:  39; coluna:  40; 


In [4]:
quantidade  = np.array( [1,2,3,4,5,6])
preco = np.array( [10,20,30,40,50,60])
faturamento = quantidade * preco
print(faturamento)

[ 10  40  90 160 250 360]


In [5]:
quantidade  =  [1,2,3,4,5,6]
preco =  [10,20,30,40,50,60]
faturamento = [ qt * pr for qt , pr in zip(quantidade,preco)]
print(faturamento)

[10, 40, 90, 160, 250, 360]


### Iteração em matrizes 3-D

In [7]:
meu_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [70, 80, 90], 
                       [100, 110, 120]
                       ]
                      ])

for x in meu_array:
  for y in x:
    for z in y:
      print(z)
    print('')
  print('')

10
20
30

40
50
60


70
80
90

100
110
120




## Simplificando a iteração com nditer ()
- Percorra todos os itens de um array multidimensional usando um único loop.

In [8]:
meu_array = np.array([
                      [
                       [10, 20, 30], 
                       [40, 50, 60]
                       ], 
                      [
                       [70, 80, 90], 
                       [100, 110, 120]
                       ]
                      ])


for x in np.nditer(meu_array):
  print(x, end=', ')

10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 

### Para alterar o tipo de dados dos elementos durante a iteração.
- Deve-se indicar o tipo de dado e se será usado um buffer durante a iteração ou se será gerado uma cópia do array.

In [9]:
meu_array = np.array([10, 20, 30, 40, 50])

for x in np.nditer(meu_array, flags=['buffered'], op_dtypes=['U']):
  print(x)

10
20
30
40
50


In [10]:
meu_array = np.array([10, 20, 30, 40, 50])

for x in np.nditer(meu_array, flags=['buffered'], op_dtypes=['f8']):
  print(x)

10.0
20.0
30.0
40.0
50.0


## Iteração enumerada com indice usando ndenumerate ()

### Iterando em array 1-D

In [11]:
meu_array = np.array([10, 20, 30, 40, 50])

for idx, x in np.ndenumerate(meu_array):
    if idx[0] % 2 == 0:
      print(idx, x)

(0,) 10
(2,) 30
(4,) 50


### Iterando em matriz 2D

In [16]:
meu_array = np.array([[21, 22, 23, 24, 25], [5, 6, 7, 8]], dtype=object)

for idposicao, valor in np.ndenumerate(meu_array):
    print("Índice:", idposicao, "Valor:", valor)

Índice: (0,) Valor: [21, 22, 23, 24, 25]
Índice: (1,) Valor: [5, 6, 7, 8]
