# Numpy - Junção / Segmentação de Arrays e Matrizes

## Juntando matrizes NumPy com np.concatenate()
- Em NumPy os arrays são unidos por eixos, usando a função concatenate(). Se o eixo não for passado explicitamente, ele será considerado 0.

### Juntando arrays 1-D

In [1]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.concatenate((arr1, arr2))

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


### Juntando matrizes 2-D ao longo das linhas (eixo = 1):

In [2]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.concatenate((arr1, arr2), axis=1)

print(meu_array)

[[10 20 50 60]
 [30 40 70 80]]


### Juntando matrizes 2-D ao longo das colunas (eixo = 0):

In [3]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.concatenate((arr1, arr2), axis=0)

print(meu_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


### Empilhamento de arrays com 1-D (apenas) np.stack()
- colocá-los um sobre o outro, ou ao lado do outro.

In [4]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.stack((arr1, arr2), axis=0)

print(meu_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [5]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.stack((arr1, arr2), axis=1)

print(meu_array)

[[ 10  60]
 [ 20  70]
 [ 30  80]
 [ 40  90]
 [ 50 100]]


### Empilhamento de arrays e matrizes ao longo das linhas usando hstack():

In [6]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.hstack((arr1, arr2))

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
', '.join([str(x) for x in np.nditer(meu_array)])

'10, 20, 30, 40, 50, 60, 70, 80, 90, 100'

In [8]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.hstack((arr1, arr2))

print(meu_array)

[[10 20 50 60]
 [30 40 70 80]]


### Empilhamento de arrays e matrizes ao longo das colunas usando vstack()

In [9]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.vstack((arr1, arr2))

print(meu_array)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]


In [10]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.vstack((arr1, arr2))

print(meu_array)

[[10 20]
 [30 40]
 [50 60]
 [70 80]]


### Empilhamento ao longo da altura usanto dstack() 

In [11]:
arr1 = np.array([10, 20, 30, 40, 50])

arr2 = np.array([60, 70, 80, 90, 100])

meu_array = np.dstack((arr1, arr2))

print(meu_array)

[[[ 10  60]
  [ 20  70]
  [ 30  80]
  [ 40  90]
  [ 50 100]]]


In [12]:
arr1 = np.array([[10, 20], 
                 [30, 40]])

arr2 = np.array([[50, 60], 
                 [70, 80]])

meu_array = np.dstack((arr1, arr2))

print(meu_array)

[[[10 50]
  [20 60]]

 [[30 70]
  [40 80]]]


## Quebra / Divisão de Matriz e Array NumPy

### Quebar usando a função array_split()
- A função array_split() pode ser usada para dividir matrizes, passamos como argumentos a matriz e o número de divisões.

- Caso o numero de elementos não seja multiplo os ultimos array terão menos elementos, mas não ocorrerá erro na operação.

In [13]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 2)

print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [14]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 3)

print(novo_array)

[array([10, 20, 30, 40]), array([50, 60, 70]), array([ 80,  90, 100])]


In [15]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.array_split(meu_array, 4)

print(novo_array)

[array([10, 20, 30]), array([40, 50, 60]), array([70, 80]), array([ 90, 100])]


In [16]:
meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])
novo_array = np.array_split(meu_array, 2)

print(novo_array)

[array([[10, 20],
       [30, 40],
       [50, 60]]), array([[ 70,  80],
       [ 90, 100],
       [110, 120]])]


In [17]:
meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(meu_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [18]:
meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.array_split(meu_array, 4)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100]]), array([[110, 120]])]


### Quebrar usando a função split()
- Esse método é similar ao array_split(), mas falha se a quantidad de elementos não for multiplo da quantidade de divisões.

In [19]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.split(meu_array, 2)

print(novo_array)

[array([10, 20, 30, 40, 50]), array([ 60,  70,  80,  90, 100])]


In [20]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = np.split(meu_array, 3)

print(novo_array)

ValueError: array split does not result in an equal division

In [ ]:
meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(meu_array, 3)

print(novo_array)

[array([[10, 20],
       [30, 40]]), array([[50, 60],
       [70, 80]]), array([[ 90, 100],
       [110, 120]])]


In [ ]:
meu_array = np.array([
                      [10, 20], 
                      [30, 40],
                      [50, 60], 
                      [70, 80],
                      [90, 100],
                      [110, 120]
                 ])

novo_array = np.split(meu_array, 4)

print(novo_array)

ValueError: array split does not result in an equal division

### Quebrar uma Matriz em arrays de valores das colunas com hsplit()

In [ ]:
meu_array = np.array([[10, 20, 30, 40, 50, 60], 
                      [70, 80, 90, 100, 110, 120], 
                      [130, 140, 150, 160, 170, 180]])

novo_array = np.hsplit(meu_array, 3)

print(novo_array)

[array([[ 10,  20],
       [ 70,  80],
       [130, 140]]), array([[ 30,  40],
       [ 90, 100],
       [150, 160]]), array([[ 50,  60],
       [110, 120],
       [170, 180]])]


### Quebrar uma Matriz em arrays de valores das linhas com vsplit()

In [ ]:
meu_array = np.array([[10, 20, 30], 
                      [40, 50, 60], 
                      [70, 80, 90], 
                      [100, 110, 120], 
                      [130, 140, 150], 
                      [160, 170, 180]])

novo_array = np.vsplit(meu_array, 3)

print(novo_array)

[array([[10, 20, 30],
       [40, 50, 60]]), array([[ 70,  80,  90],
       [100, 110, 120]]), array([[130, 140, 150],
       [160, 170, 180]])]
