# Numpy - Filtragem e Ordenação em Arrays e Matrizes

## Pesquisando valores em arrays usando o método where()

### Exemplo Encontre os índices onde o valor é 3:

In [15]:
import numpy as np

meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Encontrar os pares
encontrados_arr = np.where(meu_array % 2 == 0)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('Os valores encontrados foram {}'.format(', '.join([str(meu_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [0 1 2 3 4 5 6 7 8 9]
Os valores encontrados foram [ 10  20  30  40  50  60  70  80  90 100]


In [17]:
meu_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# Encontrar os impares
encontrados_arr = np.where(meu_array % 2 == 1)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('Os valores encontrados foram {}'.format(', '.join([str(meu_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [0 2 4 6 8]
Os valores encontrados foram [1 3 5 7 9]


In [18]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
# Encontrar os multiplos de 3
encontrados_arr = np.where(meu_array % 3 == 0)

print('As posições encontradas foram {}'.format(', '.join([str(p) for p in list(encontrados_arr)])))
print('Os valores encontrados foram {}'.format(', '.join([str(meu_array[p]) for p in list(encontrados_arr)])))

As posições encontradas foram [2 5 8]
Os valores encontrados foram [30 60 90]


## Pesquisa Ordenada para identifica onde determinado valores deveria ser inserido no array mantendo-o ordenado

In [4]:
meu_array = np.array([1, 2, 3, 4, 5, 6, 8, 9, 10])

x = np.searchsorted(meu_array, 7)

print(x)

6


In [5]:
meu_array = np.array([1, 3, 5, 7])

x = np.searchsorted(meu_array, [2, 4, 6])

print(x)

[1 2 3]


## Ordenação de matrizes usando sort()
- Colocar os elementos em uma sequência ordenada, numérico ou alfabético, crescente ou decrescente.

In [6]:
meu_array = np.array([10, 30, 60, 90, 20,100, 70, 80, 40, 50])

print(np.sort(meu_array))

[ 10  20  30  40  50  60  70  80  90 100]


In [7]:
meu_array = np.array([
                      [10, 30, 60, 90, 20,100, 70, 80, 40, 50],
                      [1, 3, 6, 9, 2,10, 7, 8, 4, 5],
                      [10, 30, 60, 90, 20,100, 70, 80, 40, 50]
])

print(np.sort(meu_array))

[[ 10  20  30  40  50  60  70  80  90 100]
 [  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [8]:
meu_array = np.array(['Norte', 'Sul', 'Leste', 'Oeste'])

print(np.sort(meu_array))

['Leste' 'Norte' 'Oeste' 'Sul']


In [9]:
meu_array = np.array([True, False, False, False, False, True, True, False, True, False])

print(np.sort(meu_array))

[False False False False False False  True  True  True  True]


## Filtrar matrizes usando uma lista de índice booleano .
- Se o valor em um índice for True o elemento é mantido, se False é excluído do resultado

In [10]:
arr1 = np.array([1,2,3,4,5])
arr1[[False, True, False, True, False]]

array([2, 4])

In [11]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print(meu_array)

filtro_multip3 = meu_array % 3 == 0
print(filtro_multip3)


array_filtrado = meu_array[filtro_multip3]
print(array_filtrado)

[ 10  20  30  40  50  60  70  80  90 100]
[False False  True False False  True False False  True False]
[30 60 90]


In [12]:
meu_array = np.array([
    [10, 20, 30, 40, 50, 60, 70, 80, 90, 100],
    [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
])

print(meu_array)

filtro_multip3 = meu_array % 3 == 0
print(filtro_multip3)


array_filtrado = meu_array[filtro_multip3]
print(array_filtrado)

[[ 10  20  30  40  50  60  70  80  90 100]
 [  1   2   3   4   5   6   7   8   9  10]
 [ 10  20  30  40  50  60  70  80  90 100]]
[[False False  True False False  True False False  True False]
 [False False  True False False  True False False  True False]
 [False False  True False False  True False False  True False]]
[30 60 90  3  6  9 30 60 90]


- Filtrar passando a expressão direta como indice

In [13]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

novo_array = meu_array[(meu_array % 3 == 0) | (meu_array % 4 == 0)  ]

print(novo_array)

[ 20  30  40  60  80  90 100]
