# Numpy - Geração de Valores Aleatórios em Arrays e Matrizes

## Gerando Números Aleatórios com o módulo random
- Número (pseudo) aleatório é aquele que não pode ser previsto logicamente.

### Gerar numeros inteiros aleatórios:


In [15]:
import numpy as np
from numpy import random

x = random.randint(30)

print(x)

2


### Gerar matriz de numeros inteiros aleatórios:

In [16]:
x=random.randint(60, size=(6))

print(x)

[30  5 43 36 38 36]


In [17]:
x = random.randint(100, size=(3, 5))

print(x)

[[82 25 11 17  5]
 [58 76 92 13 49]
 [43 61  5 45 86]]


### Gerar flutuação aleatória usando método rand() 
- Esse método retorna uma flutuação aleatória entre 0 e 1.


In [18]:
x = random.rand()

print(x)

0.4021740088538438


In [19]:
x = random.rand(5)

print(x)

[0.69027356 0.63826881 0.30549192 0.29606976 0.15712251]


In [20]:
x = random.rand(3, 5)

print(x)

[[0.86181241 0.82722497 0.83618564 0.86036119 0.2475245 ]
 [0.57826369 0.3127502  0.39563461 0.01361423 0.73972357]
 [0.9391353  0.84935697 0.62477764 0.11922569 0.0603336 ]]


### Combinando randint()  e   rand()  para gerar numero float maiores que 1

In [21]:
x=random.randint(100, size=(5)) + random.rand(5) 

print(x)

[68.81792811 14.1821313  70.43926365 22.71893949 49.72706361]


In [22]:
x=random.randint(80, 220, size=(3, 5)) + random.rand(3, 5) 

print(x)

[[129.89108652 138.30918092 113.12614018 112.48925435 168.39171906]
 [135.90691553 146.77929978 140.97914946  99.95158063 185.79583712]
 [124.77161044 207.56980201 217.84124006 143.07048277 176.81476003]]


### Gerar número aleatório a partir de uma lista predefinida usando método choice()


In [23]:
x = random.choice([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(x)

80


In [24]:
nomes= [ 'Emanuel', 'Miguel', 'Henry', 'Gael', 'Arthur Henrique', 'Luiz', 
            'José', 'Noah', 'Yago', 'André', 'Felipe', 'Pietro', 'Lucca', 
            'Raul', 'Luiz', 'Fernando', 'Eduardo', 'Ruan', 'Luiz Otávio', 
            'Davi Miguel', 'Rafael', 'Thiago', 'Oliver', 'Rodrigo', 
            'João Gabriel', 'Samuel', 'João Victor', 'Ryan', 'Pedro Miguel', 
            'Bryan', 'Enzo Gabriel', 'Pedro Henrique', 'Augusto', 'Leonardo', 
            'Kauê', 'Davi Lucas', 'Martin', 'Nicolas', 'Bernardo', 
            'Lucas Gabriel', 'Gabriel', 'Miguel Henrique', 'Lorenzo', 'Daniel',
            'Gustavo', 'Caleb', 'Danilo', 'Pedro', 'João Miguel', 'Ian', 
            'Davi', 'Anthony', 'Pedro Lucas', 'Vinícius', 'João', 'Lucas', 
            'Tomás', 'Anthony Gabriel', 'Enzo', 'Bento', 'Benjamin', 'Vicente',
            'Enzo Miguel', 'Théo', 'Fernanda Otávio', 'Matheus', 
            'Levi', 'Benício', 'Victor', 'Joaquim', 'Guilherme', 'Thomas', 
            'Enrico', 'Arthur', 'Carlos', 'Henrique', 'Luiz', 
            'João Guilherme', 'Breno', 'Davi', 'Luiz Henrique', 
            'Murilo', 'Cauã', 'Nathan', 'João Pedro', 'Yuri', 'Victor Hugo', 
            'Antônio', 'Kaique', 'Arthur Miguel', 'João Lucas', 'Caio', 
            'Davi Lucca', 'Arthur', 'Bruno', 'Luan', 'Heitor', 'Francisco', 
            'Isaac', ] 

In [25]:
x = random.choice(nomes)

print(x)

Henrique


In [26]:
x = random.choice(nomes, size=(3, 5))

print(x)

[['Levi' 'Thomas' 'Kaique' 'José' 'André']
 ['Ian' 'Emanuel' 'Pedro Lucas' 'Ruan' 'Gustavo']
 ['Gustavo' 'Ryan' 'Noah' 'João Pedro' 'Davi Miguel']]


### Permutações aleatórias de elementos shuffle() e permutation()
- shuffle() altera a disposição dos elementos  na própria matriz.


In [27]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

np.random.shuffle(meu_array)

print(meu_array)

[ 10  20  30  40  50  60  70  80  90 100]
[ 20 100  30  40  70  10  50  90  80  60]


- permutation()  retorna uma matriz reorganizada (e deixa a matriz original inalterada)

In [28]:
meu_array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print(meu_array)

novo_array = np.random.permutation(meu_array)

print(meu_array)

print(novo_array)


[ 10  20  30  40  50  60  70  80  90 100]
[ 10  20  30  40  50  60  70  80  90 100]
[ 30  80  60  70  10  40  90 100  20  50]
