# Numpy - Funções Matemáticas e Estatísticas em Arrays e Matrizes

## Ufuncs NumPy
- ufuncs são "Funções Universais" que operam no objeto ndarray por meio de vetorização (operação baseada em vetor em vez de iteracao) no NumPy, que é muito mais rápido do que iterar sobre os elementos.

- fornecem transmissão e métodos adicionais, como reduzir, acumular, entre outros.
- aceitam argumentos adicionais, como: where, dtype e out.

- operação baseada em vetor são mais rápidas porque as CPUs modernas são otimizadas para esse tipo de operações.

### Verifique a diferença de tempo de processamento entre uma mesma operação interativa e uma operação vetorial

In [5]:
import numpy as np
from numpy import random
x = np.random.randint(100, size=(10**7))
y = np.random.randint(100, size=(10**7))
z = []
print(x.shape)

(10000000,)


In [2]:
%%timeit
for i, j in zip(x, y):
  z.append(i + j)

2.87 s ± 96.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [3]:
%%timeit
z = np.add(x, y)

24.4 ms ± 1.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### O NumPy oferece uma grande quantidade de funções vetorias para diversos fins


- Cálculos matemáticos: https://numpy.org/doc/stable/reference/routines.math.html
- Cálculos estatísticos:  https://numpy.org/doc/stable/reference/routines.statistics.html

- Calculos financeiros: https://numpy.org/doc/stable/reference/routines.financial.html
- Manipulação de texto: https://numpy.org/doc/stable/reference/routines.char.html
- Algebra linear: https://numpy.org/doc/stable/reference/routines.linalg.html

## Exemplo de cálculos matemáticos

- Cálculos matemáticos: https://numpy.org/doc/stable/reference/routines.math.html


#### floor(x, /[, out, where, casting, order, …])
- Retorma o array com valor arrendondados para o inteiro menor

In [6]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

[[35.4593916  38.22163532  5.69097779 75.62155525 12.43091952]
 [88.97908642 46.53795799  9.88756685 86.61352485 41.82831898]
 [13.3468714  47.05749002 87.62483645 31.40803627 64.07108739]]


In [7]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

print(np.floor(x))

print(x)

[[68.68541514 39.77005783 88.00967959 73.83990889 93.47514803]
 [30.73491414  7.69489495 60.09407342 64.09539499 18.61243209]
 [18.44606839 18.76883423 52.52469858 55.12978386 82.42041473]]
[[68. 39. 88. 73. 93.]
 [30.  7. 60. 64. 18.]
 [18. 18. 52. 55. 82.]]
[[68.68541514 39.77005783 88.00967959 73.83990889 93.47514803]
 [30.73491414  7.69489495 60.09407342 64.09539499 18.61243209]
 [18.44606839 18.76883423 52.52469858 55.12978386 82.42041473]]


In [8]:
x= np.random.randint(100, size=(3, 5)) + np.random.rand(3, 5) 

print(x)

print(np.floor(x, out=x))

print(x)

[[58.16484511 71.34702298 69.62098459 60.17857795 91.81510221]
 [82.96279104 46.49461277  3.04719466 57.5252098  15.91818223]
 [42.76270506 63.20290034 24.69743028 63.44132575 72.0347816 ]]
[[58. 71. 69. 60. 91.]
 [82. 46.  3. 57. 15.]
 [42. 63. 24. 63. 72.]]
[[58. 71. 69. 60. 91.]
 [82. 46.  3. 57. 15.]
 [42. 63. 24. 63. 72.]]


In [24]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

resultado = np.zeros(x.shape)

print(np.floor(x, where=x>50 , out=resultado))

print(x)

print(resultado)


[[21.78994558 87.81137619 88.89390041 11.54588834 88.71884355]
 [30.94965373 52.71319196 33.52866726 92.53751567 34.25150956]
 [44.5815499  36.09971529 16.9531947   4.65845114 35.42989372]]
[[ 0. 87. 88.  0. 88.]
 [ 0. 52.  0. 92.  0.]
 [ 0.  0.  0.  0.  0.]]
[[21.78994558 87.81137619 88.89390041 11.54588834 88.71884355]
 [30.94965373 52.71319196 33.52866726 92.53751567 34.25150956]
 [44.5815499  36.09971529 16.9531947   4.65845114 35.42989372]]
[[ 0. 87. 88.  0. 88.]
 [ 0. 52.  0. 92.  0.]
 [ 0.  0.  0.  0.  0.]]


### ceil(x, /[, out, where, casting, order, …])

Retorna o inteiro superior

In [10]:
x=random.randint(100, size=(3, 5)) + random.rand(3, 5) 

print(x)

print(np.ceil(x))


[[42.22068302 51.41866054 37.11130664 81.46544987 23.14102299]
 [20.46304037 92.4136822  65.89367789  7.82047687 36.69927302]
 [99.36484775 73.92916528 91.10605592 54.05569804 66.63632151]]
[[ 43.  52.  38.  82.  24.]
 [ 21.  93.  66.   8.  37.]
 [100.  74.  92.  55.  67.]]


### prod(a[, axis, dtype, out, keepdims, …])
- Retorna o produto dos elementos de um array no eixo informado

In [11]:
# Produto das colunas
a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.prod(a,axis=0))

[[4 4]
 [3 3]
 [2 4]]
[24 48]


In [12]:
# Produto das linhas
a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.prod(a,axis=1))

[[4 3]
 [3 3]
 [4 3]]
[12  9 12]


### sum(a[, axis, dtype, out, keepdims, …])
Retorna a soma dos elementos do array para o eixo escolhido

In [13]:
# soma das colunas
a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.sum(a,axis=0))

[[3 3]
 [1 2]
 [2 4]]
[6 9]


In [14]:
# soma das linhas
a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.sum(a,axis=1))

[[4 2]
 [1 3]
 [2 4]]
[6 4 6]


### exp(x, /[, out, where, casting, order, …])
- Retorna o exponencial dos elementos de um array (e=2.718281)

In [15]:
a=random.randint(1,5, size=(3, 2)) 

print(a)

print(np.exp(a))



[[2 4]
 [2 4]
 [4 2]]
[[ 7.3890561  54.59815003]
 [ 7.3890561  54.59815003]
 [54.59815003  7.3890561 ]]


### log10(x, /[, out, where, casting, order, …])
- Retorna o logarítimo na base 10 dos elementos do array

In [16]:
a=random.randint(1000,2000, size=(3, 2)) 

print(a)

print(np.log10(a))



[[1578 1607]
 [1544 1026]
 [1731 1834]]
[[3.198107   3.20601588]
 [3.1886473  3.01114736]
 [3.23829707 3.26339933]]


## Exemplo de cálculos estatísticos

- Cálculos estatísticos:  https://numpy.org/doc/stable/reference/routines.statistics.html

### amin(a[, axis, out, keepdims, initial, where])
- Retorna o menor valor do array para o eixo informado

In [17]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.amin(a, axis=0))

print(np.amin(a, axis=1))

[[66 60 66 57 63]
 [36 43 54 35 24]
 [32 49 11 63 68]
 [35 51 17 41 18]
 [55 67 35 20 35]]
[32 43 11 20 18]
[57 24 11 17 20]


### amax(a[, axis, out, keepdims, initial, where])
- Retorna o maior valor do array para o eixo informado

In [18]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.amax(a, axis=0))

print(np.amax(a, axis=1))

[[50 17 45 57 21]
 [66 16 58 32 20]
 [13 49 25 37 65]
 [34 68 43 19 22]
 [34 47 68 10 63]]
[66 68 68 57 65]
[57 66 65 68 68]


### median(a[, axis, out, overwrite_input, keepdims])
- Retorna a mediana dos valores do array para o eixo informado

In [19]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.median(a, axis=0))

print(np.median(a, axis=1))

[[37 30 25 17 24]
 [41 59 34 28 10]
 [49 60 18 11 31]
 [48 12 17 46 60]
 [20 57 52 24 52]]
[41. 57. 25. 24. 31.]
[25. 34. 31. 46. 52.]


### average(a[, axis, weights, returned])
- Retorna a media ponderada dos valores do array para o eixo informado

In [20]:
a=random.randint(10,70, size=(5, 5)) 
print(a)

print('media coluna',np.average(a, axis=0))

print('media linha',np.average(a, axis=1))

pesos = random.randint(1,5, size=(5, 5)) 

print('pesos',pesos)

print('media ponderada coluna',np.average(a, axis=0, weights=pesos))

print('media ponderada linha',np.average(a, axis=1, weights=pesos))


[[38 27 37 65 42]
 [51 21 62 64 16]
 [29 67 14 35 19]
 [31 39 62 14 52]
 [46 28 20 41 58]]
media coluna [39.  36.4 39.  43.8 37.4]
media linha [41.8 42.8 32.8 39.6 38.6]
pesos [[4 2 4 3 3]
 [3 3 1 1 3]
 [1 1 2 2 2]
 [3 4 2 1 3]
 [1 1 1 1 4]]
media ponderada coluna [39.41666667 33.45454545 38.2        48.         40.        ]
media ponderada linha [42.1875     35.45454545 29.         41.76923077 45.875     ]


### mean(a[, axis, dtype, out, keepdims])
- Retorna a media aritmética dos valores do array para o eixo informado

In [21]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.mean(a, axis=0))

print(np.mean(a, axis=1))

[[38 22 33 20 44]
 [12 48 59 58 40]
 [22 67 65 48 63]
 [56 58 67 56 10]
 [67 24 50 40 41]]
[39.  43.8 54.8 44.4 39.6]
[31.4 43.4 53.  49.4 44.4]


### std(a[, axis, dtype, out, ddof, keepdims])
- Retorna a desvio-padrao dos valores do array para o eixo informado

In [22]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.std(a, axis=0))

print(np.std(a, axis=1))

[[24 35 63 21 62]
 [36 43 32 24 69]
 [46 26 40 16 23]
 [21 44 58 51 42]
 [56 17 29 23 57]]
[13.16966211 10.29563014 13.72005831 12.31259518 16.40243884]
[18.16590212 15.38050714 11.1067547  12.44829306 16.84755175]


### var(a[, axis, dtype, out, ddof, keepdims])
- Retorna a variância dos valores do array para o eixo informado

In [23]:
a=random.randint(10,70, size=(5, 5)) 

print(a)

print(np.var(a, axis=0))

print(np.var(a, axis=1))

[[59 56 62 33 45]
 [26 51 30 35 52]
 [41 66 68 21 53]
 [44 44 29 51 31]
 [69 21 62 47 49]]
[222.16 228.24 290.56 114.24  64.  ]
[114.   115.76 302.16  70.96 271.04]
