# Numpy - Exportação e Importação de Arrays e Matrizes para Arquivos

## Salvando Arrays em arquivos


In [1]:
import numpy as np
from numpy import random

meu_array =random.randint(10,70, size=(5, 5)) 

print(meu_array)

np.savetxt("array.csv", meu_array, delimiter=";", fmt='%s')

[[10 52 11 58 26]
 [59 60 22 27 60]
 [23 46 28 20 55]
 [40 11 43 43 68]
 [36 50 13 54 25]]


In [2]:
with open("array.csv") as f:
  print(f.read())

10;52;11;58;26
59;60;22;27;60
23;46;28;20;55
40;11;43;43;68
36;50;13;54;25



## Carregando Arrays a partir de Arquivos

In [3]:
novo_arr = np.loadtxt('array.csv', delimiter=';', skiprows=0 , dtype=float)
print(novo_arr)

[[10. 52. 11. 58. 26.]
 [59. 60. 22. 27. 60.]
 [23. 46. 28. 20. 55.]
 [40. 11. 43. 43. 68.]
 [36. 50. 13. 54. 25.]]
